source 'https://rubygems.org'

gem 'rerun'
gem 'sinatra'
gem 'thin'
gem 'restforce'
gem 'activesupport', '5.2.1'
gem 'highline'
gem 'xml-simple'
gem 'sucker_punch'
gem 'sqlite3'
gem 'sequel'
gem 'pry-byebug'
gem 'minitest'
gem 'minitest-stub_any_instance'
