username         : scott+rl@teamdecimal.com.scottk
password         : p,T$]K?":3)Q
securitytoken    : Qu9yKPBX3vWn78e7SANXDt1T3
host             : test.salesforce.com
clientid        : 3MVG9sSN_PMn8tjQyx5gkXGG2h1Qk34oEkdFg6v33HpP9YAfmTAdbw8Fpn5ucxCd29WJCQALsuJTqSRvImDdE
clientsecret    : 42AD8FB3A4F4A32E003DF47B206A17C1E02B2FBB097C5416E62D0619B6D2F6FE
